### ISSUE TITLE
Sign on top?

### ISSUE THREAD

**Issue by denebeim** [ArgusMagnus/ValheimServersideQoL#74]
No idea if this is possible, but could you put a sign on top?  One of the common ways people make more room is to put the chests almost under the floor  (or overhead as the case may be)    If you can't put it on top/bottom, perhaps you can place it like I do manually, namely the very top/bottom edge of the sign, so they protrude.

**Comment by ArgusMagnus** [comment]
Neat idea, I think that should be possible.

**Comment by ArgusMagnus** [comment]
Like [this](https://github.com/ArgusMagnus/ValheimServersideQoL/actions/runs/15685288019)?

**Comment by denebeim** [comment]
That doesn't seem to work for me.  It does put the new text into the config file, so I'm pretty sure I'm running the right version

**Comment by ArgusMagnus** [comment]
What chest did you test it on? It should look like this:

![Valheim (Game Preview)-2025_06_17-05_18_57.png](https://github.com/user-attachments/assets/ee5a8b48-d089-49c0-8793-91c5ec9173f6)

**Comment by denebeim** [comment]
I just tried it on the regular 10 slot. You know wood ones.

**Comment by denebeim** [comment]
I'm probably doing this wrong, but ChestSignOffsets.yml contains WoodChest="5,5,5,5"  and that doesn't seem to work.

Speaking of which ChestSignsDefaultText = <#fff>•
results in a blank sign.  Just the • used to work, but that doesn't seem to work either.

**Comment by ArgusMagnus** [comment]
> I'm probably doing this wrong, but ChestSignOffsets.yml contains WoodChest="5,5,5,5" and that doesn't seem to work.

Your *ChestSignOffsets.yml* should look something like this:
```
piece_chest_wood:
  Left: 0.8
  Right: 0.8
  Front: 0.4
  Back: 0.4
  Top: 1 # <- Changed from 0.8 to 1
piece_chest:
  Left: 0.85
  Right: 0.85
  Front: 0.5
  Back: 0.5
  Top: 1.1
piece_chest_blackmetal:
  Left: 0.95
  Right: 0.95
  Front: 0.7
  Back: 0.7
  Top: 0.95
incinerator:
  Left: .nan
  Right: .nan
  Front: 0.1
  Back: .nan
  Top: 3
```
Also, make sure you are editing the correct file. If `ConfigPerWorld = false` you should edit the one in *BepInEx/Config/argusmagnus.ServersideQoL*, if `ConfigPerWorld = true` you should edit the one in *worlds_local/YourWorld.ServersideQoL*

> Speaking of which ChestSignsDefaultText = <#fff>• results in a blank sign. Just the • used to work, but that doesn't seem to work either. I tried erasing the config file and recreating it, but that also resulted in blank signs.

It appears I broke default texts, should be fixed in [this build](https://github.com/ArgusMagnus/ValheimServersideQoL/actions/runs/15713732818)
